### ISSUE TITLE
Install via Composer Fails

### ISSUE THREAD

**Issue by teamayu** [luminovang/framework#1]
Thanks for this framework, but the install fails on PHP8.3.7

`Composer\Config::disableProcessTimeout

Fatal error: Cannot use 'true' as class name as it is reserved in .....luminova\bootstrap\functions.php on line 215`

**Comment by peterujah** [comment]
@teamayu I will take a look, and will release new update as soon as possible

**Comment by peterujah** [comment]
@teamayu This issue has been resolved, try composer update and the error should be gone, It is due unsupported union type.
